"""Add custom handwriting models

Revision ID: 8fa945b2bdcb
Revises:
Create Date: 2026-10-09 15:49:19.175013

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "8fa945b2bdcb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handwritingprofile",
        sa.Column("profile_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_handwritingprofile_profile_name"),
        "handwritingprofile",
        ["profile_name"],
        unique=False,
    )
    op.create_table(
        "charactersample",
        sa.Column(
            "character",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
        ),
        sa.Column("sample_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["handwritingprofile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_charactersample_character"),
        "charactersample",
        ["character"],
        unique=False,
    )
    op.create_index(
        op.f("ix_charactersample_profile_id"),
        "charactersample",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "document",
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "stored_filename",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extracted_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["handwritingprofile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_filename"), "document", ["filename"], unique=False)
    op.create_index(
        op.f("ix_document_profile_id"),
        "document",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_profile_id"), table_name="document")
    op.drop_index(op.f("ix_document_filename"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_charactersample_profile_id"), table_name="charactersample")
    op.drop_index(op.f("ix_charactersample_character"), table_name="charactersample")
    op.drop_table("charactersample")
    op.drop_index(
        op.f("ix_handwritingprofile_profile_name"),
        table_name="handwritingprofile",
    )
    op.drop_table("handwritingprofile")
    # ### end Alembic commands ###
